import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Réservation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="relative h-[500px] w-full mb-48">
        <Image
          fill={true}
          src="/assets/images/banner.webp"
          alt="banner"
          className="object-cover"
        />
        {children}
      </div>
    </>
  );
}
