import TopNavigation from "@/components/TopNavigation";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-poppins">
      <body>
        <TopNavigation />
        <div className="w-full mt-28">
          <div className="container mx-auto px-6 py-3">{children}</div>
        </div>
      </body>
    </html>
  );
}
