import "reflect-metadata";
import "@/config/container.config";
import TopNavigation from "@/components/TopNavigation";
import "@/styles/globals.css";
import "@/styles/layout.css";
import type { Metadata } from "next";
import FooterSection from "@/components/FooterSection";

export const metadata: Metadata = {
  title: "Valiha Hôtel",
  description: "Generated by Trusty Labs",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-poppins">
      <body>
        <TopNavigation />
        <main className="relative">{children}</main>
        <FooterSection />
      </body>
    </html>
  );
}
