import "@/styles/globals.css";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-poppins">
      <body>
        <header className="bg-white fixed top-0 w-full border-dark h-24">
          <nav className="container mx-auto px-6 py-3">
            <div className="flex justify-between items-center">
              <a href="#" className="text-2xl font-bold text-gray-800">
                <Image
                  src="/assets/img/logo.png"
                  alt="logo"
                  width={200}
                  height={20}
                  className="h-16"
                />
              </a>
              <div className="hidden md:flex items-center space-x-4">
                <a href="#" className="text-gray-800 hover:text-blue-600">
                  Home
                </a>
                <a href="#" className="text-gray-800 hover:text-blue-600">
                  About
                </a>
                <a href="#" className="text-gray-800 hover:text-blue-600">
                  Services
                </a>
                <a href="#" className="text-gray-800 hover:text-blue-600">
                  Contact
                </a>
                <a
                  href="#"
                  className="bg-blue-600 text-white px-4 py-2 rounded-md"
                >
                  Sign Up
                </a>
              </div>
              <div className="md:hidden flex items-center">
                <button className="text-gray-800 focus:outline-none">
                  <svg
                    className="w-6 h-6"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16"
                    ></path>
                  </svg>
                </button>
              </div>
            </div>
          </nav>
        </header>
        <div className="w-full mt-28">
          <div className="container mx-auto px-6 py-3">{children}</div>
        </div>
      </body>
    </html>
  );
}
