import { CategoryResponseDto } from "@/application/dto/category/category-response";
import { Category } from "../models/Category";
import { Room } from "../models/Room";

const CATEGORY_VALUES: CategoryResponseDto[] = [
  {
    id: "1",
    title: "Standard",
    type: "Hotel with breakfast",
    adult: 2,
    kid: 1,
    bigBed: 0,
    smallBed: 1,
    image: "/statics/categories/standard.webp",
  },
  {
    id: "3",
    title: "Deluxe Double",
    type: "Hotel with breakfast",
    adult: 2,
    kid: 1,
    bigBed: 1,
    smallBed: 0,
    image: "/statics/categories/deluxeDouble.webp",
  },
  {
    id: "5",
    title: "Family Room",
    type: "Hotel with breakfast",
    adult: 2,
    kid: 2,
    bigBed: 1,
    smallBed: 2,
    image: "/statics/categories/familyRoom.webp",
  },
  {
    id: "2",
    title: "Deluxe Twin",
    type: "Hotel with breakfast",
    adult: 2,
    kid: 1,
    bigBed: 0,
    smallBed: 2,
    image: "/statics/categories/deluxeTwin.webp",
  },
  {
    id: "4",
    title: "Chambre Triple",
    type: "Hotel with breakfast",
    adult: 3,
    kid: 1,
    bigBed: 1,
    smallBed: 1,
    image: "/statics/categories/triple.webp",
  },
  {
    id: "6",
    title: "Appartement",
    type: "Apartment with Kitchen",
    adult: 2,
    kid: 1,
    bigBed: 1,
    smallBed: 1,
    image: "/statics/categories/appart.webp",
  },
];

export const ROOM_VALUES: Room[] = [
  {
    id: "64c8e422a3b66fbd287ac5ce",
    title: "202",
    price: 150000,
    image: "/statics/rooms/202Standard.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c0",
      title: "Standard",
      type: "Hôtel avec petit-déjeuner",
      adult: 2,
      kid: 1,
      bigBed: 1,
      smallBed: 0,
      image: "/statics/categories/standard.webp",
    },
  },
  {
    id: "64c8e422a3b66fbd287ac5cf",
    title: "204",
    price: 180000,
    image: "/statics/rooms/1deluxeDouble.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c1",
      title: "Deluxe Double",
      type: "Hôtel avec petit-déjeuner",
      adult: 10,
      kid: 8,
      bigBed: 2,
      smallBed: 3,
      image: "/statics/categories/deluxeDouble.webp",
    },
  },
  {
    id: "64c8e422a3b66fbd287ac5d0",
    title: "205 | Familiale",
    price: 245000,
    image: "/statics/rooms/familyRoom.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c2",
      title: "Chambre Familiale",
      type: "Hôtel avec petit-déjeuner",
      adult: 4,
      kid: 3,
      bigBed: 1,
      smallBed: 1,
      image: "/statics/categories/familyRoom.webp",
    },
  },
  {
    id: "64c8e422a3b66fbd287ac5d1",
    title: "203",
    price: 160000,
    image: "/statics/rooms/deluxeTwin.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c3",
      title: "Deluxe Twin",
      type: "Hôtel avec petit-déjeuner",
      adult: 1,
      kid: 8,
      bigBed: 1,
      smallBed: 3,
      image: "/statics/categories/deluxeTwin.webp",
    },
  },
  {
    id: "64c8e422a3b66fbd287ac5d2",
    title: "205 | Triple",
    price: 210000,
    image: "/statics/rooms/triple.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c4",
      title: "Chambre Triple",
      type: "Hôtel avec petit-déjeuner",
      adult: 4,
      kid: 1,
      bigBed: 3,
      smallBed: 1,
      image: "/statics/categories/triple.webp",
    },
  },
  {
    id: "64ca1c067963cd9a9e655a9b",
    title: "302",
    price: 150000,
    image: "/statics/rooms/302Standard.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c0",
      title: "Standard",
      type: "Hôtel avec petit-déjeuner",
      adult: 2,
      kid: 1,
      bigBed: 1,
      smallBed: 0,
      image: "/statics/categories/standard.webp",
    },
  },
  {
    id: "64ca35884170d4e94e2ce837",
    title: "301",
    price: 210000,
    image: "/statics/rooms/301Appart.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c5",
      title: "Appartment",
      type: "Appartement avec Cuisine", // Champ type mis à jour
      adult: 8,
      kid: 8,
      bigBed: 0,
      smallBed: 3,
      image: "/statics/categories/appart.webp",
    },
  },
  {
    id: "64ca37844170d4e94e2ce83a",
    title: "304",
    price: 180000,
    image: "/statics/rooms/1deluxeDouble.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c1",
      title: "Deluxe Double",
      type: "Hôtel avec petit-déjeuner",
      adult: 10,
      kid: 8,
      bigBed: 2,
      smallBed: 3,
      image: "/statics/categories/deluxeDouble.webp",
    },
  },
  {
    id: "64ca37f44170d4e94e2ce83c",
    title: "305 | Familiale",
    price: 245000,
    image: "/statics/rooms/familyRoom.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c1",
      title: "Deluxe Double",
      type: "Hôtel avec petit-déjeuner",
      adult: 10,
      kid: 8,
      bigBed: 2,
      smallBed: 3,
      image: "/statics/categories/deluxeDouble.webp",
    },
  },
  {
    id: "64ca38824170d4e94e2ce83d",
    title: "303",
    price: 160000,
    image: "/statics/rooms/deluxeTwin.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c3",
      title: "Deluxe Twin",
      type: "Hôtel avec petit-déjeuner",
      adult: 1,
      kid: 8,
      bigBed: 1,
      smallBed: 3,
      image: "/statics/categories/deluxeTwin.webp",
    },
  },
  {
    id: "64ca390a4170d4e94e2ce83e",
    title: "305 | Triple",
    price: 210000,
    image: "/statics/rooms/triple.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c4",
      title: "Chambre Triple",
      type: "Hôtel avec petit-déjeuner",
      adult: 4,
      kid: 1,
      bigBed: 3,
      smallBed: 1,
      image: "/statics/categories/triple.webp",
    },
  },
  {
    id: "64ca39e24170d4e94e2ce841",
    title: "201",
    price: 210000,
    image: "/statics/rooms/201Appart.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c5",
      title: "Appartment",
      type: "Appartement avec Cuisine", // Champ type mis à jour
      adult: 8,
      kid: 8,
      bigBed: 0,
      smallBed: 3,
      image: "/statics/categories/appart.webp",
    },
  },
  {
    id: "64ca3c334170d4e94e2ce842",
    title: "203 | Standard",
    price: 150000,
    image: "/statics/rooms/202Standard.webp",
    category: {
      id: "64c8e422a3b66fbd287ac5c0",
      title: "Standard",
      type: "Hôtel avec petit-déjeuner",
      adult: 2,
      kid: 1,
      bigBed: 1,
      smallBed: 0,
      image: "/statics/categories/standard.webp",
    },
  },
];

export default CATEGORY_VALUES;
